name: End-to-end Tests

on:
  #schedule:
    # Runs our tests at the top of every hour
  #  - cron:  '0 * * * *'
  workflow_dispatch:

env:
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  DATADOG_CUSTOMER: "OpenDialog"
  VIRTUAL_DEVICE_TOKEN: OpenDialog
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npx yarn install 
      
      - name: Test
        run: npm run e2e
      
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test_output
          path: test_output
